export const AWS_S3 = 'aws_s3'
export const AWS_FUNCTION = 'aws_function'
export const EVENT_S3 = 'event_s3'
export const EVENT_DYNAMODB_STREAM = 'event_dynamodb_stream'
export const AWS_DYNAMODB = 'aws_dynamodb'